# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc7afa1996f32e5f35876cb1f39e7db3f3aa1c2a925999c0eab0dd5dfddd7a8c141ba4756f58a948f689e60fd550c53e9fe69fd50625127626210fd5b0c8a5fa

test:
  secret_key_base: 43153f6f350b32825a81933bbd3d1473529efc82779f6283532d2b856457d1baf3dbd35a4ab85f92dbeeb321b023fa193cd7ed5dd8768979365b8ef25ff2aa6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
